### PR TITLE
Create a machine-specific configuration for gstreamer1.0-plugin-vspfilter

### PR DESCRIPTION
**Pull request by dl9pf**
This avoids the binary package to be rebuilt based on the board.
Instead only the -config subpackage is being rebuilt.

Signed-off-by: Jan-Simon Möller <dl9pf@gmx.de>

### CODE REVIEW

**Comment by harunobukurokawa** [comment]
Hi @dl9pf , 

Thank you for your suggestion.

we will accept your commit, but we must modify commit title and message in our side. Next release we will apply your modification.
Thanks.

Best regards,
Kurokawa.

**Comment by dl9pf** [comment]
This is no problem, go ahead.

**Comment by khangnguyenrvc** [comment]
Hi @dl9pf 

The patch was merged fbb75874506639be3822624192080901a0ce4c13

Best Regards,
Khang,

**Comment by harunobukurokawa** [comment]
merged

**Pull request closed without merging**
