### PR TITLE
*.inc: prepend the layer name to global .inc files

### PR DESCRIPTION
**Pull request by fredcadete**
This avoids conflicts with other layers that may have .inc files
with the same name.

Signed-off-by: Frederico Cadete frederico.cadete@awtce.be

### CODE REVIEW

**Comment by tasaito** [comment]
Please explain procedure reproducing conflict. 

Now, meta-renesas is a recipe which append to poky. 
It is not conflicting between meta-renesas and poky. 
The include file which does not conflict by meta-your-layer should be able to implement.

Regards

**Comment by fredcadete** [comment]
Hello Saito-san,

I am sorry, you are correct, it is not easy to understand the patch purpose with just the commit message.

In out Yocto setup, we use the same set of layers to build for R-Car Gen2 and R-Car Gen3. For R-Car Gen2, the layer also has files named, for example, "gles-control.inc"
We use BBMASK to choose the correct set of .bb and .bbappend files.
But BBMASK does not affect .inc files. So, when a recipe in meta-rcar-gen3 does "include gles-control.inc", it will get the file from meta-rcar-gen2.
The same conflict could happen with any other layer that has a file named "gles-control.inc"

A possible way to avoid this conflict is to have .inc files named in a layer-specific way. This was suggested in the yocto IRC: https://www.yoctoproject.org/irc/%23yocto.2016-06-15.log.html#t2016-06-15T17:42:43.
It is also followed by meta-intel: http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel/tree/conf/machine/include

Regards,
Frederico

**Comment by tasaito** [comment]
Hi Frederico-san,

There is no schedule which supports Gen2 in jethro branch.
But the conflict of Gen2 and Gen3 is explained. 

meta-rcar-gen3 layer is dependent on Gen3.
For build Gen3, current bblayers.conf has setup "meta-renesas/meta-rcar-gen3".
meta-rcar-gen3/include/*.inc are only for Gen3 clearly. 

Similarly, in Gen2, it is "meta-renesas/meta-rcar-gen2". 
Don't include "meta-renesas/meta-rcar-gen3" in Gen2. 
Layer should be controlled by bblayers.conf.
(Please refer to docs/sample/conf)

In Gen2 and Gen3, ARM arch and Compiler (includes compiler option) differs.
It is build separately. 
There is no meaning which integrated to the same build directory.
We recommend separating build directory of Gen2 and Gen3.
(bblayers.conf and local.conf are not the same)

source poky/oe-init-build-env ${BUILD_DIR_GEN3}
cd ${BUILD_DIR_GEN3}

Regards,

**Comment by fredcadete** [comment]
Got it. Please disregard this pull request then.

**Pull request closed without merging**
